name: Run Script on PR

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run MiAction
      uses: ./.github/actions/miaction
    
    - name: Summary Part 1
      run: |
        echo "## Plugins Results" >> $GITHUB_STEP_SUMMARY
        echo "| Name | Last Version | Last Version PR | New Version Deployed| New Version |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|--------|------------------|-------------|" >> $GITHUB_STEP_SUMMARY
        echo "| Plugin A | 1.0.0 | 1.0.1 | 1.0.2 | 1.0.3 |" >> $GITHUB_STEP_SUMMARY

    - name: Summary Part 2
      run: |
        echo "## Services Results" >> $GITHUB_STEP_SUMMARY
        echo "| Name | Last Version | Last Version PR | New Version Deployed| New Version |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|--------|------------------|-------------|" >> $GITHUB_STEP_SUMMARY
        echo "| Service A | 1.0.0 | 1.0.1 | 1.0.2 | 1.0.3 |" >> $GITHUB_STEP_SUMMARY